"""Generate the UTF-8 <-> GBK tables used by the on-device serial output.
Only characters the model's tokenizer can emit are needed: walk the vocabulary,
decode each token to text and keep the ones with a 2-byte GBK form.
Writes main/gbk_table.cpp (two sorted arrays for binary search).
"""
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def main():
    model_dir = sys.argv[1]
    default_out = Path(__file__).resolve().parents[1] / "main" / "gbk_table.cpp"
    out_c = Path(sys.argv[2]) if len(sys.argv) > 2 else default_out
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(model_dir)
    vocab_size = len(tok)
    cps = set()
    for i in range(vocab_size):
        text = tok.decode([i], skip_special_tokens=False, clean_up_tokenization_spaces=False)
        for ch in text:
            if ord(ch) < 0x80:
                continue
            try:
                two = ch.encode("gbk")
            except UnicodeEncodeError:
                continue
            if len(two) == 2:
                cps.add(ord(ch))
    for ch in "协议每行输入一句话回车发送模型按内容流式返回空行退出编码已切换只支持或":
        try:
            if len(ch.encode("gbk")) == 2:
                cps.add(ord(ch))
        except UnicodeEncodeError:
            pass
    pairs = sorted((cp, int.from_bytes(chr(cp).encode("gbk"), "big")) for cp in cps)
    print(f"vocab {vocab_size}: {len(pairs)} codepoints with a 2-byte GBK form")
    head = [
        "/* Generated by tools/gen_gbk_table.py -- do not edit by hand.",
        " * u2g: sorted by unicode codepoint; g2u: sorted by GBK code. */",
        '#include "gbk_table.h"',
        f"const int g_gbk_count = {len(pairs)};",
        "const uint32_t g_gbk_u2g_cp[] = {",
    ]
    lines = list(head)
    lines += ["    " + ",".join(f"0x{c:04X}" for c, _ in pairs[i:i + 12]) + ","
              for i in range(0, len(pairs), 12)]
    lines.append("};")
    lines.append("const uint16_t g_gbk_u2g_val[] = {")
    lines += ["    " + ",".join(f"0x{v:04X}" for _, v in pairs[i:i + 12]) + ","
              for i in range(0, len(pairs), 12)]
    lines.append("};")
    g2u = sorted((v, c) for c, v in pairs)
    lines.append("const uint16_t g_gbk_g2u_val[] = {")
    lines += ["    " + ",".join(f"0x{v:04X}" for v, _ in g2u[i:i + 12]) + ","
              for i in range(0, len(g2u), 12)]
    lines.append("};")
    lines.append("const uint32_t g_gbk_g2u_cp[] = {")
    lines += ["    " + ",".join(f"0x{c:04X}" for _, c in g2u[i:i + 12]) + ","
              for i in range(0, len(g2u), 12)]
    lines.append("};")
    out_c.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_c} ({out_c.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
